SELECT 
MATNOSG.REGION_CODE AS Region
,MATNOSG.PRODUCT_MIX AS LOBMix_noXH
,DT.CALENDAR_DATE AS Report_Date
--,DT.Scenario

, SUM( ZEROIFNULL(MATNOSG.X1_PLATFORM_IND)) AS X1_Connects
, SUM(ZEROIFNULL(MATNOSG.B1)) AS B1_ConnectsV

FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG MATNOSG
JOIN NDW_SHARED_VIEWS.DATE_DIM_BASE_V DT 
		ON MATNOSG.EFFECTIVE_DATE = DT.CALENDAR_DATE

JOIN (SELECT EFFECTIVE_DATE, 
 			CASE WHEN MONTH_END_DT= (SELECT MAX(MONTH_END_DT) from EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG) 
 						THEN 'Y' ELSE 'N' END AS CurrFMEflag
			FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG
			GROUP BY EFFECTIVE_DATE, MONTH_END_DT) AS FLAG
		ON MATNOSG.EFFECTIVE_DATE= FLAG.EFFECTIVE_DATE
                                
WHERE MATNOSG.ACTIVITY = 'CONNECT'
AND MATNOSG.DIVISION_NAME= 'NORTHEAST DIVISION'
AND PRODUCT_MIX NOT LIKE '%XH%'
AND ZEROIFNULL(MATNOSG.B1)<>0
AND FLAG.CurrFMEflag = 'Y'
--and DTPY.Scenario <> 'PYFuture'
AND MATNOSG.CUSTOMER_TYPE= 'RESIDENTIAL'
GROUP BY MATNOSG.REGION_CODE
,DT.CALENDAR_DATE
--,DTPY.Scenario
,MATNOSG.PRODUCT_MIX
ORDER BY DT.CALENDAR_DATE