SELECT MAT.REGION_CODE AS REGION 
, MAT.MONTH_END_DT AS FME
, MAT.DMA_NAME
, CASE WHEN MAT.DEMO_FIBER = 1 THEN 'Fiber' ELSE 'NonFiber' END AS Fiber
, CASE WHEN MAT.DEMO_INCOME_CODE IN ('<15K', '15-25K', '25-35K') THEN 'Low (<30k)'
  WHEN MAT.DEMO_INCOME_CODE IN ('35-50K', '50-75K') THEN 'Med (30-75K)' 
  ELSE 'High >75K' END AS Income
  , CASE WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'COMMERCIAL' THEN 'BUSINESS'
WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'MDU' THEN 'MDU'
WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'SFU' THEN 'SFU'
WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'EXCLUDE MAPPING' THEN 'EXCLUDE MAPPING'
WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'OTHER' THEN 'OTHER'
  END AS Dwell
--, REG.Level_1
--, REG.Top_Cities
, COUNT (MAT.HOUSE_NUMBER) AS HHP
, SUM (MAT.B1) AS B1
, SUM (MAT.HSI) AS HSI
, SUM (MAT.CDV) AS CDV
, SUM (MAT.HS) AS XH 

FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY MAT
JOIN NDW_BASE_VIEWS.LOCATION_HIST LH
		ON MAT.LOCATION_ID= LH.LOCATION_ID

WHERE MAT.MONTH_END_DT > (CURRENT_DATE -30)

AND  LH.VIDEO_SERVICABILITY_IND <> 'N'

AND MAT.REGION_CODE = 'KEY'
AND MAT.PRIN <> 0

GROUP BY MAT.MONTH_END_DT
, MAT.REGION_CODE
, MAT.DMA_NAME
, CASE WHEN MAT.DEMO_FIBER = 1 THEN 'Fiber' ELSE 'NonFiber' END
--, REG.Level_1
--, REG.Top_Cities
, CASE WHEN MAT.DEMO_INCOME_CODE IN ('<15K', '15-25K', '25-35K') THEN 'Low (<30k)'
	WHEN MAT.DEMO_INCOME_CODE IN ('35-50K', '50-75K') THEN 'Med (30-75K)' 
	ELSE 'High >75K' END
, CASE WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'COMMERCIAL' THEN 'BUSINESS'
	WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'MDU' THEN 'MDU'
	WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'SFU' THEN 'SFU'
	WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'EXCLUDE MAPPING' THEN 'EXCLUDE MAPPING'
	WHEN MAT.DWELL_TYPE_GROUP_BILLER = 'OTHER' THEN 'OTHER'
  	END