--SQLs Example
--DFW:
SELECT
MAT.REGION_NAME AS REGION
, MAT.REGION_CODE 
, MAT.SYSCORP
, MAT.PRIN
, MAT.AGNTFTAX
--, m.DST_House
--, m.DST_Cust
, MAT.MONTH_END_DT AS FME
, MAT.SERVICE_ORDER_CREATED_DATE AS Entered_Date
, MAT.EFFECTIVE_DATE
, MAT.SCHEDULED_DATE
, MAT.ACCOUNT_NUMBER
, MAT.HOUSE_NUMBER
, MAT.ORDER_NUM AS Order_Number
, MAT.ORDER_STATUS
, MAT.ACTIVITY
, MAT.ACTIVITYDETAIL
, MAT.CUSTOMER_TYPE AS Bus_Res
, MAT.B1
, MAT.HSI
, MAT.CDV
, MAT.HS
--, m.TriplePlayPackage
--, m.PackageName
--, m.PackageCodes
, MAT.SALES_REP_ID AS SalesID
, MAT.OP_ID AS OprID
--, m.SalesLKPTable
, MAT.SOURCE_DISCONNECT_CODE AS DiscoCode
, MAT.DISCO_REASON_ROLLUP_NM AS DiscoReason
, MAT.DISCO_REASON_ROLLUP_GROUP_NM AS DiscoSubReason
, MAT.SAMOTO_CD AS SaMoto
, MAT.CMCST_SUPER_SEG AS SuperSegment
, MAT.DEMO_INCOME_CODE AS IncomeCode
, MAT.ETHNICITY_CODE AS Ethnicity
, MAT.DWELL_TYPE_GROUP_BILLER AS DwellType
--, m.DWELLCODE
, MAT.COMPLEX_CD AS Complex
, MAT.CITY
, MAT.STATE
, MAT.ZIP AS ZIPCODE
, MAT.PRODUCT_MIX AS LOBMix
, MAT.B1_MONTHLY_FLAG AS B1_Flag
, MAT.HSI_MONTHLY_FLAG AS HSI_Flag
, MAT.CDV_MONTHLY_FLAG AS CDV_Flag
, MAT.HS_MONTHLY_FLAG AS HS_Flag
--, m.Bulk_House
--, m.FME_OrderDate
 
, SCLV.SALESCHANNELDETAIL
, SCLV.SALESCHANNEL AS SalesChannel
, SCLV.SALESCHANNELROLLUP
 
, CASE WHEN SCLV.SALESCHANNEL = '3rd Party Outsourcer' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Billing & Collections' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Repair'  THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Call Center Unknown' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Inbound Sales' THEN 'Inbound Sales'
  WHEN SCLV.SALESCHANNEL = 'In-House DSR' THEN 'In House'
  WHEN SCLV.SALESCHANNEL = 'Front Counter' THEN 'Cable Store'
  WHEN SCLV.SALESCHANNEL = 'Contract DSR' THEN 'Contractor'
  WHEN SCLV.SALESCHANNEL = 'Commercial' THEN 'Commercial'
  WHEN SCLV.SALESCHANNEL = 'Retention' THEN 'Retention' ELSE 'Other' END AS SalesChannel_T
--, [Region SOS roll-up].[DFW SOS]  -- will add lookup field to the tbl_Saleschannel_Lookup
FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY MAT
    LEFT JOIN EBI_NSD_VIEWS.SALESCHANNEL_LOOKUP_V SCLV
    ON MAT.FINAL_SALES_CHANNEL= SCLV.SALESCHANNELDETAIL
   
    
WHERE MAT.REGION_CODE='KEY'
AND MAT.SERVICE_ORDER_CREATED_DATE BETWEEN TO_DATE('2015-07-22','YYYY-MM-DD') AND TO_DATE('2015-08-21','YYYY-MM-DD')
AND (MAT.ORDER_STATUS = 'CANCELLED' OR MAT.ORDER_STATUS= 'PENDING' )
AND MAT.ACTIVITY='CONNECT'


UNION ALL

SELECT 
MATNOMSG.REGION_NAME AS REGION
, MATNOMSG.REGION_CODE
, MATNOMSG.SYSCORP
, MATNOMSG.PRIN
, MATNOMSG.AGNTFTAX
--, sg.DST_House
--, sg.DST_Cust
, MATNOMSG.MONTH_END_DT AS FME
, MATNOMSG.SERVICE_ORDER_CREATED_DATE AS Entered_Date
, MATNOMSG.EFFECTIVE_DATE
, MATNOMSG.SCHEDULED_DATE
, MATNOMSG.ACCOUNT_NUMBER
, MATNOMSG.HOUSE_NUMBER
, MATNOMSG.ORDER_NUM AS Order_Number
, ' ' AS ORDER_STATUS
, MATNOMSG.ACTIVITY
, MATNOMSG.ACTIVITYDETAIL
, MATNOMSG.CUSTOMER_TYPE AS Bus_Res
, MATNOMSG.B1
, MATNOMSG.HSI
, MATNOMSG.CDV
, MATNOMSG.HS
--, sg.TriplePlayPackage
--, sg.PackageName
--, sg.PackageCodes
, MATNOMSG.SALES_REP_ID AS SalesID
, MATNOMSG.OP_ID AS OprID
--, sg.SalesLKPTable
, MATNOMSG.SOURCE_DISCONNECT_CODE AS DiscoCode
, MATNOMSG.DISCO_REASON_ROLLUP_NM AS DiscoReason
, MATNOMSG.DISCO_REASON_ROLLUP_GROUP_NM AS DiscoSubReason
, MATNOMSG.SAMOTO_CD AS SaMoto
, MATNOMSG.CMCST_SUPER_SEG AS SuperSegment
, MATNOMSG.DEMO_INCOME_CODE AS IncomeCode
, MATNOMSG.ETHNICITY_CODE AS Ethnicity
, MATNOMSG.DWELL_TYPE_GROUP_BILLER AS DwellType
--, MATNOMSG.DWELLCODE
, MATNOMSG.COMPLEX_CD AS Complex
, MATNOMSG.City
, MATNOMSG.State
, MATNOMSG.ZIP AS ZIPCODE
, MATNOMSG.PRODUCT_MIX AS LOBMix
, MATNOMSG.B1_MONTHLY_FLAG AS B1_Flag
, MATNOMSG.HSI_MONTHLY_FLAG AS HSI_Flag
, MATNOMSG.CDV_MONTHLY_FLAG AS CDV_Flag
, MATNOMSG.HS_MONTHLY_FLAG AS HS_Flag
--, sg.Bulk_House
--, ' ' AS [FME_OrderDate]

, SCLV.SALESCHANNELDETAIL
, SCLV.SALESCHANNEL AS SalesChannel
, SCLV.SALESCHANNELROLLUP

, CASE WHEN SCLV.SALESCHANNEL = '3rd Party Outsourcer' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Billing & Collections' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Repair' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Call Center Unknown' THEN 'Billing & Repair'
  WHEN SCLV.SALESCHANNEL = 'Inbound Sales' THEN 'Inbound Sales'
  WHEN SCLV.SALESCHANNEL = 'In-House DSR' THEN 'In House'
  WHEN SCLV.SALESCHANNEL = 'Front Counter' THEN 'Cable Store'
  WHEN SCLV.SALESCHANNEL = 'Contract DSR' THEN 'Contractor'
  WHEN SCLV.SALESCHANNEL = 'Commercial' THEN 'Commercial'
  WHEN SCLV.SALESCHANNEL = 'Retention' THEN 'Retention' ELSE 'Other' END AS SalesChannel_T
--, [Region SOS roll-up].[DFW SOS]  -- will add lookup field to the tbl_Saleschannel_Lookup
FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG MATNOMSG
	LEFT JOIN EBI_NSD_VIEWS.SALESCHANNEL_LOOKUP_V SCLV
    ON MATNOMSG.FINAL_SALES_CHANNEL= SCLV.SALESCHANNELDETAIL
	

WHERE MATNOMSG.REGION_CODE='key'
AND MATNOMSG.SERVICE_ORDER_CREATED_DATE BETWEEN TO_DATE('2015-08-22','YYYY-MM-DD') AND TO_DATE('2015-09-21','YYYY-MM-DD')
AND MATNOMSG.ACTIVITY = 'connect'