SELECT 
MAT.MONTH_END_DT AS FME
, CASE WHEN MAT.ACTIVITY = 'DISCONNECT' THEN - COUNT(MAT.ACCOUNT_NUMBER) ELSE COUNT(MAT.ACCOUNT_NUMBER) END AS Accts
, CASE WHEN MAT.PRODUCT_MIX='VIDEO/HSD' THEN 'VD' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/CDV' THEN 'VDT' 
               WHEN MAT.PRODUCT_MIX='VIDEO/CDV' THEN 'VT' 
               WHEN MAT.PRODUCT_MIX='CDV ONLY' THEN 'T' 
               WHEN MAT.PRODUCT_MIX='VIDEO ONLY' THEN 'V' 
               WHEN MAT.PRODUCT_MIX='HSD/CDV/XH' THEN 'DTH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/CDV/XH' THEN 'VDTH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/XH' THEN 'VDH' 
               WHEN MAT.PRODUCT_MIX='HSD ONLY' THEN 'D' 
               WHEN MAT.PRODUCT_MIX='HSD/XH' THEN 'DH' 
               WHEN MAT.PRODUCT_MIX='XH ONLY' THEN 'H' 
               WHEN MAT.PRODUCT_MIX='HSD/CDV' THEN 'DT' 
               WHEN MAT.PRODUCT_MIX='CDV/XH' THEN 'TH'
               WHEN MAT.PRODUCT_MIX='VIDEO/XH' THEN 'VH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/XH' THEN 'VTH' 
               END AS LOBMix
, MAT.ACTIVITY
, MAT.ACTIVITYDETAIL
, MAT.FINAL_SALES_CHANNEL
FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY AS MAT
WHERE MAT.MONTH_END_DT = TO_DATE('07/21/2016','MM/DD/YYYY')
AND MAT.DIVISION_NAME= 'NORTHEAST DIVISION'
AND ORDER_STATUS = 'COMPLETED'
AND FINAL_SALES_CHANNEL<> 'MACRO'
GROUP BY MAT.MONTH_END_DT
,  MAT.ACTIVITY
, MAT.ACTIVITYDETAIL
, MAT.FINAL_SALES_CHANNEL
, CASE WHEN MAT.PRODUCT_MIX='VIDEO/HSD' THEN 'VD' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/CDV' THEN 'VDT' 
               WHEN MAT.PRODUCT_MIX='VIDEO/CDV' THEN 'VT' 
               WHEN MAT.PRODUCT_MIX='CDV ONLY' THEN 'T' 
               WHEN MAT.PRODUCT_MIX='VIDEO ONLY' THEN 'V' 
               WHEN MAT.PRODUCT_MIX='HSD/CDV/XH' THEN 'DTH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/CDV/XH' THEN 'VDTH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/XH' THEN 'VDH' 
               WHEN MAT.PRODUCT_MIX='HSD ONLY' THEN 'D' 
               WHEN MAT.PRODUCT_MIX='HSD/XH' THEN 'DH' 
               WHEN MAT.PRODUCT_MIX='XH ONLY' THEN 'H' 
               WHEN MAT.PRODUCT_MIX='HSD/CDV' THEN 'DT' 
               WHEN MAT.PRODUCT_MIX='CDV/XH' THEN 'TH'
               WHEN MAT.PRODUCT_MIX='VIDEO/XH' THEN 'VH' 
               WHEN MAT.PRODUCT_MIX='VIDEO/HSD/XH' THEN 'VTH' 
               END