SELECT Distinct
REGION_NAME AS REGION
, ACCOUNT_NUMBER AS Account_Number
, MONTH_END_DT AS fme
, EFFECTIVE_DATE AS Effective_Date
, ORDER_STATUS AS Order_Status
, ACTIVITY AS Activity
, CASE customer_type 
	when 'BUSINESS SERVICE' THEN 'BUSINESS'
	when 'RESIDENTIAL' THEN 'RESIDENTIAL'
	ELSE NULL
END AS Bus_Res
, B1
, HSI
, CDV
, HS
FROM
EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG

WHERE REGION_NAME = 'Western New England Region'
AND ORDER_STATUS = 'Completed'
AND MONTH_END_DT = '2016-03-21'