SELECT
MATNOMSG.ACCOUNT_NUMBER,
MATNOMSG.ORDER_IS_SIK_IND SIK,
CASE WHEN MATNOMSG.PRODUCT_MIX = 'VIDEO ONLY' THEN 'V' 
 	WHEN MATNOMSG.PRODUCT_MIX = 'HSD ONLY' THEN 'D'
 	WHEN MATNOMSG.PRODUCT_MIX = 'CDV ONLY' THEN 'T'
 	WHEN MATNOMSG.PRODUCT_MIX = 'HSD/CDV' THEN 'DT'
 	WHEN MATNOMSG.PRODUCT_MIX = 'VIDEO/HSD' THEN 'VD'
 	WHEN MATNOMSG.PRODUCT_MIX = 'VIDEO/HSD/CDV' THEN 'VDT'
 	WHEN MATNOMSG.PRODUCT_MIX = 'VIDEO/CDV' THEN 'VT'
ELSE NULL END LOBMIX_NOXH,
MATNOMSG.ACTIVITY,
MATNOMSG.ACTIVITYDETAIL,
MATNOMSG.MONTH_END_DT FME,
MATNOMSG.WEEK_END_DT Friday_Week_Ending,
MATNOMSG.FINAL_SALES_CHANNEL SALESCHANNEL,
MATNOMSG.FINAL_SALES_CHANNEL SALESCHANNELROLLUP,
MATNOMSG.SALES_REP_ID,
WID.MAIN_GROUP,
WID.SUB_GROUP,
WID.JOB_FUNC_NME,
WID.JOB_TTL_NME,
WID.PERNR,
WID.CSG_REP,
WID.EMP_NAME,
WID.SUP_NAME,
WID.MGR_NAME,
WID.DIR_NAME,
MATNOMSG.FINAL_SALES_CHANNEL PACKAGENAME,
MATNOMSG.X1_PLATFORM_IND

FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY_NO_M_SG MATNOMSG

LEFT JOIN NDW_TEMP.WNE_IDS WID
ON MATNOMSG.SALES_REP_ID = WID.CSG_REP

WHERE MATNOMSG.REGION_NAME = 'Western New England Region'
AND MATNOMSG.ACTIVITYDETAIL = 'NEW CONNECT'
AND MATNOMSG.MONTH_END_DT BETWEEN '2016-01-21' AND '2016-05-21'
AND MATNOMSG.PRODUCT_MIX IN ('VIDEO ONLY', 'HSD ONLY', 'CDV ONLY', 'VIDEO/HSD', 'VIDEO/CDV', 'HSD/CDV', 'VIDEO/HSD/CDV')
AND MATNOMSG.FINAL_SALES_CHANNEL IN ('Call Center SALES', 'Call Center RETENTION', 'Call Center CARE', 'Direct Sales Contractor', 'Direct Sales Inhouse', 'Front Counter', 'RETAIL', 'Dot Com')
